version: '3.3'
services:
    python:
        build: .
        restart: always 
        ports: 
            - "5000:5000"
        volumes:
            - "./:/www"
        environment:
            - FLASK_APP=hello.py